vsphere_user = "OAI@cloud-temple.lan"
vsphere_pass = "Polytec123*"
vsphere_server = "vc-vstack-019-test.virtualstack.tn"
root_pass = "oumayma123*"
vsphere_datacenter = "DC-DTX1"
vsphere_datastore = "ds001-test-svc1-stor3-dtx1"
name_rp =  "RP1"
vsphere_network = "CTT-Stage2022"
vsphere_template = "Template"
vsphere_cluster = "Clu001-PROD"

